### PR TITLE
Made messages use less space (while still looking nice)

### PR DESCRIPTION
**Pull request by greduan**
A pic would explain it the best:

2014-09-15-164812_1280x800_scrot

Notifications need a little bit more work though.

### CODE REVIEW

**Comment by raamdev** [comment]
Nice! I like this. I actually forgot that I customized my SlackMagic CSS to make things a lot tighter in the Compact mode and I lost those changes when I upgraded to the latest SlackMagic release. :(

> Notifications need a little bit more work though.

Can you post a screenshot to better describe what you mean? I'd be happy to help out on that.

**Comment by greduan** [comment]
@raamdev 

> Can you post a screenshot to better describe what you mean? I'd be happy to help out on that.

2014-09-15-165321_1280x800_scrot

I just gotta play a bit more with the margins and paddings I guess, or make those icons smaller...

**Comment by jaswrks** [comment]
Nice! If you guys can try to prefix lines that are intended specifically for the compact mode, with `.dense_theme`, that could help in certain cases. It would allow you to apply certain styles to the compact mode specifically.

Example...

```
.dense_theme #msgs_div > .message { margin: 2px; }
```

**Comment by greduan** [comment]
BTW Jason, do I have permission to go over the CSS and clean it up? It's so hard to read. lol

I mean I understand you are being specific with your rules, that's fine, but goddamn some crap is hard to read from so much specificity. lol (if that's a word)

**Comment by jaswrks** [comment]
> BTW Jason, do I have permission to go over the CSS and clean it up?

:thumbsup: Absolutely, always room for improvement! You might open a new issue/PR for this task, just so we can all review your changes and decide on which ones to merge.

Regarding specificity... just try to keep in mind that with an app like this (one that is really just a large collection of hacks against an evolving application maintained by a 3rd-party); specificity can be very helpful. If something changes in the Slack app, it will be easier for us to spot that, and update the application so that it remains in a good working state over a longer period of time.

**Comment by greduan** [comment]
OK. I think for now I'll just add a line between each rule.

You guys can merge this whenever though.

**Comment by raamdev** [comment]
@Greduan If you don't mind, I'd like to add some more tweaks so that these changes only apply to the Compact theme in Slack, and also tweak the bot messages a bit to get them more compact.

We have two options for making this happen: 
1. I'll create my own fork, based on your fork, and then submit a new Pull Request with those changes.
2. You can add me as a collaborator to your SlackMagic fork, and then I push my commits directly to your fork, which would then update this Pull Request with my commits. 

Any preference?

**Comment by greduan** [comment]
The latter would be a simpler solution. :) Just a sec...

**Comment by jaswrks** [comment]
On the topic of making things smaller... I remember when I first started working on SlackMagic, I was looking for a clean way to reduce the font size overall. I found that to be difficult given the DOM used by Slack's app. However, I did find some success in simply changing the zoom level in Chrome. It came to my attention that Chrome preserves your zoom preferences for specific URLs. So setting your zoom level to around 90% can certainly help to increase the amount of data that is visible.

**Comment by greduan** [comment]
Yeah Chrome is really cool about zoom. Thanks for the tip. :)

**Comment by jaswrks** [comment]
One of the things that bugs me about SlackMagic and the current Compact Mode (i.e. `.dense_theme`) is that our notifications still include the icons for each notification sender, whereas each of us do not have them. It almost appears (in this mode) like we give notifications more attention than they deserve. I'd love to see that improved too.

**Comment by raamdev** [comment]
> One of the things that bugs me about SlackMagic and the current Compact Mode (i.e. .dense_theme) is that our notifications still include the icons for each notification sender, whereas each of us do not have them. It almost appears (in this mode) like we give notifications more attention than they deserve. I'd love to see that improved too.

I've managed to remove those (haven't pushed the commits yet; still working on it).

## 

One thing I'd really like to decrease is the verbosity of the bot messages when using Compact mode. For example, most bot messages contain two or more lines of text. In Compact mode, it would be nice to only show the first line, which gives us the gist of the message.

However, this these other lines are not wrapped in any HTML element that we can reference with CSS, so we'd need to use JavaScript to remove them, somehow stripping out anything that comes after the first `<br>` tag in a bot message (including the `<br>` tag itself.

**Comment by raamdev** [comment]
While we're at this:

Another huge thing I miss from HipChat is the color-coded bot messages. For example, any bot message from ZenDesk could have an orange background, GitHub a light grey background, WordPress.org a light blue background, etc. The point being, in Compact mode these background colors would help us more quickly scan and see which messages are from where (if we remove icons in Compact mode, there will be no visual indicator for where the bot message came from).

However, like the issue in my previous comment, there is no way to do this using CSS. We'd need to use JavaScript to read the value of each bot message and detect which ones are from ZenDesk, GitHub, etc., and then apply the corresponding background color style.

My JavaScript skills are rusty. :(

**Comment by raamdev** [comment]
Screenshot of Compact mode as of my last commit:

**Comment by raamdev** [comment]
Removed overall messages area padding:

**Comment by jaswrks** [comment]
> decrease is the verbosity of the bot messages when using Compact mode.

Here is a way that _might_ work, with CSS only.

```
.dense_theme #msgs_div > .message.bot_message:not(.via-hipchat) > .message_content
{
    vertical-align : middle !important;
    display        : inline-block !important;
    height         : 1.15rem !important;
    overflow-y     : hidden !important;
}
```

**Comment by jaswrks** [comment]
@raamdev 

> color-coded bot messages
> 
> However, like the issue in my previous comment, there is no way to do this using CSS. We'd need to use JavaScript to read the value of each bot message and detect which ones are from ZenDesk, GitHub, etc., and then apply the corresponding background color style.

I just updated `threads.js` in the dev branch (along with the fluidapp and Safari extension). SlackMagic now adds `via-xxxx` classes that should help you pull this off. You could try applying CSS based on the `via-xxxxx` classes that are now applied to each `.message` div container.

**Comment by greduan** [comment]
Wow Raam and Jason! That stuff is looking awesome! :D

**Comment by raamdev** [comment]
> SlackMagic now adds via-xxxx classes that should help you pull this off.

Wooooohoooooo! This is just awesome. Thank you!

**Comment by raamdev** [comment]
> Here is a way that might work, with CSS only.

Yes! Thank you! I actually had the exact same idea last night, but due to my extreme tiredness the thought slipped by before I had the chance to implement it. ;)

**Comment by raamdev** [comment]
Okay, wow, that was a lot of work. Color-coded bot messages, timestamp on righthand side, and margins tightened up:



---

I think with the color-coding, it actually looks a lot more readable with multiple-line bot messages:



---

However, I'll leave the additional bot message lines hidden for now, since the goal for the Compact mode is to, well, be compact.

Also, you might want to adjust the message height (search `slackstastic.css` for "Message height"). I'm leaving `2px` as the default (seen in the first screenshot above, but here's what `5px` would look like:

**Comment by raamdev** [comment]
@jaswsinc If you're fine with these changes, can you merge this Pull Request in? @greduan might want to make some customizations for himself and if he commits those to his fork, they'll override the commits in this PR.

**Comment by jaswrks** [comment]
Very cool! Merged these changes in :-)

**Pull request merged**
